apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: spark-master
  name: spark-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: spark-master
    spec:
      containers:
      - name : spark-master
        image: kamaljain83/spark-2.1.1
        imagePullPolicy: "Always"
        name: spark-master
        ports:
        - containerPort: 7077
          protocol: TCP
        command:
         - "/start-master-home.sh"