FROM java:openjdk-8-jdk

ENV spark_ver 2.1.1

# Get Spark from US Apache mirror.
RUN mkdir -p /opt && \
    cd /opt && \
    curl http://www.us.apache.org/dist/spark/spark-${spark_ver}/spark-${spark_ver}-bin-hadoop2.7.tgz | \
        tar -zx && \
    ln -s spark-${spark_ver}-bin-hadoop2.7 spark && \
    echo Spark ${spark_ver} installed in /opt


ADD start-common-home.sh start-worker-home.sh start-master-home.sh /
RUN chmod +x /start-common-home.sh /start-master-home.sh /start-worker-home.sh
ENV PATH $PATH:/opt/spark/bin

